Enhance test system
- Tests are now named
- Testlogs are preserved between runs
- Tests can be run through Valgrind Memcheck tool

diff --git a/test/run-test b/test/run-test
--- a/test/run-test
+++ b/test/run-test
@@ -1,27 +1,50 @@
-cleanup() {
-    rm -rf $TMPDIR
-}
-trap cleanup 0
+VALGRIND_CMDLINE="valgrind --leak-check=full --show-reachable=yes --track-origins=yes -q"
 
 run_testprog() {
     local prog=$1
-    local input=$2
+    local prefix=$2
+    if [ -n "$VALGRIND" ]; then
+        local runner="$VALGRIND_CMDLINE "
+    fi
+
     case "$prog" in
         load_dump)
-            ./$prog $input $TMPDIR/output 2>$TMPDIR/error
+            $runner./$prog \
+                $prefix.in \
+                $prefix.$prog.stdout \
+                2>$prefix.$prog.stderr
             ;;
         *)
-            ./$prog <$input >$TMPDIR/output 2>$TMPDIR/error
+            $runner./$prog \
+                <$prefix.in \
+                >$prefix.$prog.stdout \
+                2>$prefix.$prog.stderr
             ;;
     esac
+
+    if [ -n "$VALGRIND" ]; then
+        # Check for Valgrind error output. The valgrind option
+        # --error-exitcode is not enough because Valgrind doesn't
+        # think unfreed allocs are errors.
+        if grep -E -q '^==[0-9]+== ' $prefix.$prog.stderr; then
+            echo "### $prefix ($prog) failed:" >&2
+            echo "valgrind detected an error" >&2
+            echo "for details, see test/$prefix.$prog.stderr" >&2
+            exit 1
+        fi
+    fi
 }
 
+rm -rf testlogs
+
 for testfile in $TESTFILES; do
-    mkdir -p $TMPDIR
-    ${srcdir}/split-testfile.py $testfile $TMPDIR | while read input output; do
-        run_test load_dump $input $output
-        run_test loadf_dumpf $input $output
-        run_test loads_dumps $input $output
+    tmpdir="testlogs/`basename $testfile`"
+    mkdir -p $tmpdir
+    ${srcdir}/split-testfile.py $testfile $tmpdir | while read name; do
+        run_test load_dump $tmpdir/$name
+        run_test loadf_dumpf $tmpdir/$name
+        run_test loads_dumps $tmpdir/$name
+        echo -n '.'
     done || exit 1
-    rm -rf $TMPDIR
+    echo
 done
diff --git a/test/test-invalid b/test/test-invalid
--- a/test/test-invalid
+++ b/test/test-invalid
@@ -1,20 +1,20 @@
 #!/bin/sh
 
 TESTFILES="${srcdir}/testdata/invalid ${srcdir}/testdata/invalid-unicode"
-TMPDIR="tmp"
 
 run_test() {
     local prog=$1
-    local input=$2
-    local output=$3
-    run_testprog $prog $TMPDIR/$input
-    if ! cmp $TMPDIR/$output $TMPDIR/error >/dev/null; then
-        echo "### $input ($prog) failed:" >&2
-        cat $TMPDIR/$input >&2
+    local prefix=$2
+
+    run_testprog $prog $prefix
+    if ! cmp $prefix.out $prefix.$prog.stderr >/dev/null; then
+        echo >&2
+        echo "### $prefix ($prog) failed:" >&2
+        cat $prefix.in >&2
         echo "### expected output:" >&2
-        cat $TMPDIR/$output >&2
+        cat $prefix.out >&2
         echo "### actual output:" >&2
-        cat $TMPDIR/error >&2
+        cat $prefix.$prog.stderr >&2
         exit 1
     fi
 }
diff --git a/test/test-valid b/test/test-valid
--- a/test/test-valid
+++ b/test/test-valid
@@ -1,30 +1,29 @@
 #!/bin/sh
 
 TESTFILES="${srcdir}/testdata/valid"
-TMPDIR="tmp"
 
 run_test() {
     local prog=$1
-    local input=$2
-    local output=$3
-    run_testprog $prog $TMPDIR/$input
-    if ! ${srcdir}/json-compare.py $TMPDIR/$input $TMPDIR/output \
-        >$TMPDIR/cmp-output
+    local prefix=$2
+
+    run_testprog $prog $prefix
+
+    if ! ${srcdir}/json-compare.py $prefix.in $prefix.$prog.stdout \
+        >$prefix.$prog.cmp-stdout
     then
-        echo "### $input ($prog) failed:" >&2
-        cat $TMPDIR/$input >&2
-        if [ -f $TMPDIR/output ]; then
+        echo >&2
+        echo "### $prefix ($prog) failed:" >&2
+        cat $prefix.in >&2
+        if [ -f $prefix.$prog.stdout ]; then
             echo "### output:" >&2
-            cat $TMPDIR/output >&2
+            cat $prefix.$prog.stdout >&2
         fi
-        if [ -s $TMPDIR/cmp-output ]; then
+        if [ -s $prefix.$prog.stdout ]; then
             echo "### compare output:" >&2
-            cat $TMPDIR/cmp-output >&2
+            cat $prefix.$prog.cmp-stdout >&2
         fi
         exit 1
     fi
-    rm -f $TMPDIR/output
-    rm -f $TMPDIR/cmp-output
 }
 
 . ${srcdir}/run-test
